version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5673:5673
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 120s


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  filter:
    build:
      context: ./filter
      dockerfile: Dockerfile
    container_name: filter_service

    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  screamer:
    build:
      context: ./screamer
      dockerfile: Dockerfile
    container_name: screamer_service

    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672


  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: publisher_service

    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672