services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - 15673:15673
      - 5673:5673

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5673

  filter:
    build:
      context: ./filter
      dockerfile: Dockerfile
    container_name: filter_service

    depends_on:
      - rabbitmq

    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5673
